### PR TITLE
Add Swift Package Manager Support

### PR DESCRIPTION
**Pull request by kgn**
Added Package.swift

### CODE REVIEW

**Comment by franci98** [comment]
This looks great! Thanks for implementing the support.

**Comment by kgn** [comment]
@franci98 will this be merged in?

**Comment by pubertoblanco** [comment]
@franci98 It would be really nice, if you could merge in :)

**Comment by nicolasproske** [comment]
Please consider to merge it soon, would be really helpful for a lot of projects! 👍 @franci98

**Comment by afern247** [comment]
Can you merge this please

**Review by afern247 — APPROVED** [review]

**Review by afern247 — CHANGES_REQUESTED** [review]
When I try to import using your fork it says:

`Package resolution failed`

**Comment by YagnikBavishi04** [comment]
Thank you for creating the PR. We have added SPM support and fixed the open issue in [2.0.0](https://github.com/SimformSolutionsPvtLtd/SSSwiftUIGIFView/releases/tag/2.0.0). Please use the latest version for SPM support. I will close this PR.

**Pull request closed without merging**
